import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://practicesoftwaretesting.com/');
  await page.locator('[data-test="nav-sign-in"]').click();
  await page.locator('[data-test="email"]').click();
  await page.locator('[data-test="email"]').click();
  await page.locator('[data-test="email"]').fill('customer@practicesoftwaretesting.com');
  await page.locator('[data-test="password"]').click();
  await page.locator('[data-test="password"]').click();
  await page.locator('[data-test="password"]').fill('welcome01');
  await page.locator('[data-test="login-submit"]').click();
  await page.locator('[data-test="nav-home"]').click();
  await page.locator('[data-test="product-01KQZE0YFKCH9ZNWJKFBVCGZKP"]').click();
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('[data-test="add-to-cart"]').click();
  await page.locator('[data-test="nav-cart"]').click();
  await page.locator('[data-test="proceed-1"]').click();
  await page.locator('[data-test="proceed-2"]').click();
  await page.getByText('CountryYour country *AlbaniaÅ').click();
  await page.locator('[data-test="country"]').selectOption('AZ');
  await page.getByText('CountryYour country *AlbaniaÅ').click();
  await page.locator('[data-test="house_number"]').click();
  await page.locator('[data-test="house_number"]').fill('45');
  await page.locator('div').filter({ hasText: 'Billing AddressCountryYour' }).nth(3).click();
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('[data-test="state"]').click();
  await page.locator('[data-test="state"]').fill('assd');
  await page.locator('app-address > .container > div > .col-md-6.offset-md-3 > .float-end').click();
  await page.locator('[data-test="postal_code"]').click();
  await page.locator('[data-test="postal_code"]').fill('454455');
  await page.locator('[data-test="proceed-3"]').click();
  await page.locator('[data-test="payment-method"]').selectOption('buy-now-pay-later');
  await page.locator('[data-test="monthly_installments"]').selectOption('3');
  await page.locator('[data-test="finish"]').click();
  await page.locator('[data-test="finish"]').click();
});