import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://practicesoftwaretesting.com/');
  await page.locator('[data-test="nav-sign-in"]').click();
  await page.locator('[data-test="email"]').click();
  await page.locator('[data-test="email"]').fill('customer@practicesoftwaretesting.com');
  await page.locator('[data-test="password"]').click();
  await page.locator('[data-test="password"]').fill('welcome01');
  await page.locator('[data-test="login-submit"]').click();
  await page.locator('[data-test="nav-home"]').click();
  await page.locator('[data-test="search-query"]').click();
  await page.locator('[data-test="search-query"]').fill('hammer');
  await page.locator('[data-test="search-submit"]').click();
  await page.locator('[data-test="search-reset"]').click();
  await page.locator('[data-test="search-query"]').click();
  await page.locator('[data-test="search-query"]').fill('crew');
  await page.locator('[data-test="search-query"]').click();
  await page.locator('[data-test="search-query"]').press('ArrowLeft');
  await page.locator('[data-test="search-query"]').press('ArrowLeft');
  await page.locator('[data-test="search-query"]').press('ArrowLeft');
  await page.locator('[data-test="search-query"]').fill('screw');
  await page.locator('[data-test="search-submit"]').click();
  await page.locator('[data-test="search-reset"]').click();
  await page.locator('[data-test="search-query"]').click();
  await page.locator('[data-test="search-query"]').fill('basket');
  await page.locator('[data-test="search-submit"]').click();
  await page.locator('[data-test="search-reset"]').click();
  await page.locator('[data-test="search-query"]').click();
  await page.locator('[data-test="search-query"]').fill('car');
  await page.locator('[data-test="search-submit"]').click();
  await page.locator('[data-test="search-reset"]').click();
  await page.locator('[data-test="search-query"]').click();
  await page.locator('[data-test="search-query"]').fill('basket');
  await page.locator('[data-test="search-submit"]').click();
  await page.locator('[data-test="no-results"]').click();
});